CREATE TABLE DIM_SYS_DATE_SCHEMA
(
  ID                             INTEGER,
  JULIAN_DAY                     INTEGER,
  SYS_DATE                       DATE,
  YEAR_4DIGIT                    INTEGER,
  YEAR_2DIGIT                    NUMBER(2),
  QUARTER_OF_YEAR                INTEGER,
  QUARTERS_LEFT_IN_YEAR          INTEGER,
  MONTH_FULL_NM                  VARCHAR2(10 CHAR),
  MONTH_ABBR_NM                  VARCHAR2(3 CHAR),
  MONTH_OF_YEAR                  INTEGER,
  MONTH_OF_QUARTER               INTEGER,
  MONTHS_LEFT_IN_YEAR            INTEGER,
  MONTHS_LEFT_IN_QUARTER         INTEGER,
  WEEK_OF_YEAR                   INTEGER,
  WEEK_OF_QUARTER                INTEGER,
  WEEK_OF_MONTH                  INTEGER,
  WEEKS_LEFT_IN_YEAR             INTEGER,
  WEEKS_LEFT_IN_QUARTER          INTEGER,
  WEEKS_LEFT_IN_MONTH            INTEGER,
  DAY_OF_WEEK_FULL_NM            VARCHAR2(10 CHAR),
  DAY_OF_WEEK_ABBR_NM            VARCHAR2(3 CHAR),
  DAY_OF_YEAR                    INTEGER,
  DAY_OF_QUARTER                 INTEGER,
  DAY_OF_MONTH                   INTEGER,
  DAY_OF_WEEK                    INTEGER,
  DAY_OF_BUSINESS_WEEK           INTEGER,
  SUNDAY_OF_MONTH                INTEGER,
  MONDAY_OF_MONTH                INTEGER,
  TUESDAY_OF_MONTH               INTEGER,
  WEDNESDAY_OF_MONTH             INTEGER,
  THURSDAY_OF_MONTH              INTEGER,
  FRIDAY_OF_MONTH                INTEGER,
  SATURDAY_OF_MONTH              INTEGER,
  SUNDAYS_IN_MONTH               INTEGER,
  MONDAYS_IN_MONTH               INTEGER,
  TUESDAYS_IN_MONTH              INTEGER,
  WEDNESDAYS_IN_MONTH            INTEGER,
  THURSDAYS_IN_MONTH             INTEGER,
  FRIDAYS_IN_MONTH               INTEGER,
  SATURDAYS_IN_MONTH             INTEGER,
  DAYS_LEFT_IN_YEAR              INTEGER,
  DAYS_LEFT_IN_QUARTER           INTEGER,
  DAYS_LEFT_IN_MONTH             INTEGER,
  DAYS_LEFT_IN_WEEK              INTEGER,
  DAYS_LEFT_IN_BUSINESS_WEEK     INTEGER,
  IS_TODAY                       NUMBER(1),
  IS_PAST                        NUMBER(1),
  IS_FUTURE                      NUMBER(1),
  IS_WEEKDAY                     NUMBER(1),
  IS_WEEKEND                     NUMBER(1),
  IS_LEAP_DAY                    NUMBER(1),
  IS_LEAP_YEAR                   NUMBER(1),
  IS_FIRST_DAY_OF_YEAR           NUMBER(1),
  IS_FIRST_DAY_OF_QUARTER        NUMBER(1),
  IS_FIRST_DAY_OF_MONTH          NUMBER(1),
  IS_FIRST_DAY_OF_WEEK           NUMBER(1),
  IS_FIRST_DAY_OF_BUSINESS_WEEK  NUMBER(1),
  IS_LAST_DAY_OF_YEAR            NUMBER(1),
  IS_LAST_DAY_OF_QUARTER         NUMBER(1),
  IS_LAST_DAY_OF_MONTH           NUMBER(1),
  IS_LAST_DAY_OF_WEEK            NUMBER(1),
  IS_LAST_DAY_OF_BUSINESS_WEEK   NUMBER(1)
);